### ISSUE TITLE
Discuss about: How to instrument the ServiceComb SDK

### ISSUE THREAD

**Issue by wu-sheng** [ApacheInfra/ServiceComb-Java-Chassis#127]
Hi, everyone, I am from [sky-walking](https://github.com/wu-sheng/sky-walking) team, which is an open source APM hosted on GitHub. We are also an opentracing supported tracer.

As ServiceComb has 4 releases, even they are all pre-release versions(from the version number is 0.x), I wonder that the framework core is stabilization enough to add some instrumentation codes or provide our team some intercept points about auto instrumentation agent do its works.

Skywalking has many supported from Chinese contributors, so we want to support Chinese open source RPC framework first. We have already supported Dubbo/Dubbox, Motan, Hprose(by OT API) , and been cooperating with dangdang.com about linkerd instrumentation and Sharding-JDBC instrumentation.

If your team has interested in instrumentation about micro-service, even event-bus, maybe we can cooperate on these things. Welcome to ping @wu-sheng and @sky-walking, when you have time or think it's ready to go.

**Comment by WillemJiang** [comment]
Hi wu-sheng,

It's great that you can offer instrumentation support from the Skywalking.  We already implemented the tracing by using zipkin[1][2] in Java-chassis 0.2.0.  Can you take a look at it? Please let me know if you have any question about it.
 
[1]https://github.com/ServiceComb/ServiceComb-Java-Chassis/pull/78
[2]https://github.com/ServiceComb/ServiceComb-Java-Chassis/pull/86

**Comment by wu-sheng** [comment]
I do a quick review #78, I think almost all the tracing stuffs are included in `io.servicecomb#handler-tracing-zipkin`, so there is too much things to review. BTW, Zipkin API is easy enough to use.

Only a suggestion is , in #78, you can find English(Most all), French(Log), Chinese(a few comments) are all used, maybe you can do some adjustments.

And a name, **Highway** , is it a new protocol provided by ServiceComb? A new high performance network protocol?

For #86, it depends on Zuul-Zipkin, so have less to say.

___

For skywalking, we need a stabilize classes/methods names to set the intercept point, for creating/stopping span, and set tags. Do you have any suggestion to do that?

**Comment by seanyinx** [comment]
@wu-sheng 

It's great to get help from you and skywalking team on integration with open source tracing solutions.

You are right. *Highway* is a new high performance communication protocol defined in ServiceComb.

Maybe we can continue this discussion on our [developer mailing list](https://groups.google.com/forum/#!forum/servicecomb-developers), so that more people, including the original team who developed Java Chassis from scratch, can participate and easier for us to follow?

**Comment by wu-sheng** [comment]
@seanyinx Hi, I just join the group, and post a discussion there: https://groups.google.com/forum/#!topic/servicecomb-developers/fL612WnlTWI

**Comment by wu-sheng** [comment]
And I hope to keep this issue open, because I am a GitHub fun, but not really a Google fun.

**Comment by lijasonvip** [comment]
@wu-sheng,  thanks for your kind attention, this issue will be closed before next Monday if there is no further question about it, because all unsolved issues will be moved to Apache JIRA in next Mondy. Anyway, you can still follow us or open an issue at Apache JIRA https://issues.apache.org/jira/projects/SCB Thanks again!

**Comment by wu-sheng** [comment]
Sure. I am closing this. And @WillemJiang We are going to continue using GitHub issues as bug track, which I think it is much easier for users.
